[package]
name = "rgb-std"
version = "0.8.0-beta.1"
license = "MIT"
authors = ["Dr Maxim Orlovsky <orlovsky@lnp-bp.org>"]
description = "RGB Standard Library: high-level API for private & scalable client-validated smart contracts on Bitcoin & Lightning"
repository = "https://github.com/RGB-WG/rgb-std"
homepage = "https://rgb.network"
keywords = ["bitcoin", "lightning", "rgb", "smart-contracts", "lnp-bp"]
categories = ["cryptography::cryptocurrencies"]
readme = "README.md"
edition = "2021"
rust-version = "1.59.0"
exclude = [".github", "contrib"]

[lib]
name = "rgb"

[[bin]]
name = "rgb"
path = "src/bin/rgb.rs"
required-features = ["cli", "serde"]

[dependencies]
amplify = "3.12.0"
lnpbp_bech32 = "0.7.0"
strict_encoding = { version = "~1.8.8", features = ["crypto", "chrono", "bitcoin"] }
commit_verify = "0.7.0"
bp-core = "0.7.0"
rgb_core = { package = "rgb-core", version = "0.8.0-alpha.1", git = "https://github.com/RGB-WG/rgb-core" }
descriptor-wallet = { version = "~0.7.1", features = ["descriptors"] }
bitcoin = "0.28.1"
electrum-client = { version = "0.10.0", optional = true }
serde_crate = { package = "serde", version = "1", features = ["derive"], optional = true }
serde_with = { version = "1.8", features = ["hex"], optional = true }
serde_yaml = { version = "0.8", optional = true }
serde_json = { version = "1", optional = true }
clap = { version = "~3.1.18", optional = true, features = ["derive"] }

[dev-dependencies]
serde_json = "1"

[features]
default = ["serde", "cli"]
all = ["serde", "cli", "wallet"]
wallet = ["rgb_core/wallet", "bp-core/wallet"]
cli = ["clap", "serde_yaml", "serde_json", "descriptor-wallet/electrum", "electrum-client"]
serde = ["serde_crate", "serde_with", "lnpbp_bech32/serde",
    "amplify/serde", "commit_verify/serde", "strict_encoding/serde", "rgb_core/serde",
    "amplify/serde", "descriptor-wallet/serde", "bp-core/serde",
    "bitcoin/use-serde"]
